ARG ELASTICSEARCH_VERSION=latest
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}

# Add healthcheck
#COPY ./scripts/docker-healthcheck .
#HEALTHCHECK CMD sh ./docker-healthcheck

# EXPOSE 9200 9300
