ARG REDIS_STACK_VERSION=latest
FROM redis/redis-stack:${REDIS_STACK_VERSION}

LABEL maintainer="zaizai <33045134@qq.com>"

# 不生效
# COPY ./redis-stack.conf /redis-stack.conf
# COPY ./sources.list /sources.list
# ENTRYPOINT ["/entrypoint.sh"]