ARG DTM_VERSION=latest
FROM yedf/dtm:${DTM_VERSION}

LABEL maintainer="zz <373045134@qq.com>"

# COPY ./config.yml /app/dtm/configs/config.yaml

# ENTRYPOINT ["/app/dtm/dtm", "-c", "/app/dtm/configs/config.yaml"]