volumes:
  redis-box:
    driver: ${VOLUMES_DRIVER}

services:
### REDIS BOX ##############################################
  redis-box:
    build:
      context: ${REDIS_BOX_HOST_PATH}
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: ${REDIS_BOX_CONTAINER_NAME}
    hostname: ${REDIS_BOX_HOSTNAME}
    command: "sleep infinity"
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "${REDIS_BOX_HOST_PORT}:6379"
    environment:
      - "TZ=${TZ}"
      - "CLUSTER_CREATE=${REDIS_CLUSTER_CREATE} ${REDIS_CLUSTER_ADDRESS} --cluster-replicas 1 --cluster-yes"
      - "CLUSTER_CHECK=${REDIS_CLUSTER_CHECK} ${REDIS_CONTAINER_NAME_NODE1}:${REDIS_BACKEND_IP_NODE1}"
      - "CONNECT_NODE=redis-cli -a ${REDIS_PASSWORD} -p ${REDIS_CONTAINER_PORT} -h ${REDIS_BACKEND_IP_NODE1}"
    networks:
      frontend:
        ipv4_address: ${REDIS_BOX_FRONTEND_IP}
      backend:
        ipv4_address: ${REDIS_BOX_BACKEND_IP}